
version: '3.1'

services: 

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password 
    ports: 
       - "8081:3306"
    environment:
      MYSQL_DATABASE: MMS
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  medmanagesystem:
    depends_on:
      - db
      - mq
    build: ./medmanagesystem
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:3306/MMS?useSSL=true",
        "spring.datasource.username" : "user",
        "spring.datasource.password" : "user",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.rabbitmq.host" : "localhost",
        "spring.rabbitmq.port" : 5672,
        "spring.rabbitmq.username" : "guest",
        "spring.rabbitmq.password": "guest",
        "server.port": 8000

        }'
    ports: 
      - 6666:8000
    restart: on-failure
    
  mq:
    image: rabbitmq:management
    ports:
      - 5672:5672 
      - 15672:15672

#  datagen:
#    build: ./sensor/
#    restart: on-failure
#    container_name: data_gen
#    depends_on:
#      - mq
#      - db
#      - medmanagesystem
volumes:
  datafiles:
